version: '2'
services:
    go-pddl-app:
        build: 
            context: ..
            dockerfile: ./docker/Dockerfile
        volumes:
            - ../:/go/src/github.com/guilyx/go-pddl
            - ./volumes/go/pkg:/go/pkg
        ports:
            - 8080
        environment:
            - ENV=dev